-- =============================================================
-- GENERATED FILE — do not edit by hand.
-- Source: supabase/syllabus.json  ·  Regenerate: npm run syllabus:sql
-- Subject → Theme → Topic → Subtopic tree for every supported subject.
-- =============================================================

insert into public.subjects (slug, name, group_name, description, color, sort_order) values
  ('math-aa', 'Mathematics: Analysis & Approaches', 'Mathematics', 'Algebra, functions, calculus and proof with an emphasis on analytical methods.', '#B92A5A', 1),
  ('math-ai', 'Mathematics: Applications & Interpretation', 'Mathematics', 'Modelling, statistics and applied mathematics supported by technology.', '#7A4FB0', 2),
  ('physics', 'Physics', 'Sciences', 'Motion, matter, waves, fields and the quantum world.', '#2B6E8F', 3),
  ('chemistry', 'Chemistry', 'Sciences', 'Structure and reactivity: how matter is built and how it changes.', '#2F8F6B', 4),
  ('biology', 'Biology', 'Sciences', 'Unity and diversity, form and function, interaction and continuity.', '#3F8F2F', 5),
  ('economics', 'Economics', 'Individuals & Societies', 'Scarcity and choice, markets, national policy and the global economy.', '#C6892B', 6),
  ('global-politics', 'Global Politics', 'Individuals & Societies', 'Power, rights, development, peace and conflict in a global context.', '#B0483C', 7),
  ('psychology', 'Psychology', 'Individuals & Societies', 'Biological, cognitive and sociocultural approaches to behaviour.', '#2E7D8F', 8),
  ('philosophy', 'Philosophy', 'Individuals & Societies', 'Being human, optional themes, prescribed texts and the HL extension.', '#6A5AA8', 9),
  ('world-religions', 'World Religions', 'Individuals & Societies', 'Beliefs, practices and lived experience across the world''s religions.', '#A0662B', 10)
on conflict (slug) do update set
  name = excluded.name, group_name = excluded.group_name,
  description = excluded.description, color = excluded.color,
  sort_order = excluded.sort_order;

insert into public.levels (subject_id, code, name, sort_order)
select s.id, l.code, l.name, l.sort_order
from public.subjects s
cross join (values ('SL', 'Standard Level', 1), ('HL', 'Higher Level', 2)) as l(code, name, sort_order)
on conflict (subject_id, code) do nothing;

insert into public.themes (subject_id, slug, name, description, level_code, sort_order)
select s.id, t.slug, t.name, t.description, t.level_code, t.sort_order
from public.subjects s
join (values
  ('math-aa', 'number-algebra', 'Number & Algebra', null, null, 1),
  ('math-aa', 'functions', 'Functions', null, null, 2),
  ('math-aa', 'geometry-trigonometry', 'Geometry & Trigonometry', null, null, 3),
  ('math-aa', 'statistics-probability', 'Statistics & Probability', null, null, 4),
  ('math-aa', 'calculus', 'Calculus', null, null, 5),
  ('math-ai', 'number-algebra', 'Number & Algebra', null, null, 1),
  ('math-ai', 'functions', 'Functions', null, null, 2),
  ('math-ai', 'geometry-trigonometry', 'Geometry & Trigonometry', null, null, 3),
  ('math-ai', 'statistics-probability', 'Statistics & Probability', null, null, 4),
  ('math-ai', 'calculus', 'Calculus', null, null, 5),
  ('math-ai', 'discrete-mathematics', 'Discrete Mathematics', null, null, 6),
  ('physics', 'space-time-motion', 'Space, Time and Motion', null, null, 1),
  ('physics', 'particulate-nature-of-matter', 'The Particulate Nature of Matter', null, null, 2),
  ('physics', 'wave-behaviour', 'Wave Behaviour', null, null, 3),
  ('physics', 'fields', 'Fields', null, null, 4),
  ('physics', 'nuclear-quantum-physics', 'Nuclear and Quantum Physics', null, null, 5),
  ('chemistry', 'structure-1-particulate-nature', 'Structure 1 — Models of the Particulate Nature of Matter', null, null, 1),
  ('chemistry', 'structure-2-bonding', 'Structure 2 — Models of Bonding and Structure', null, null, 2),
  ('chemistry', 'structure-3-classification', 'Structure 3 — Classification of Matter', null, null, 3),
  ('chemistry', 'reactivity-1-what-drives-reactions', 'Reactivity 1 — What Drives Reactions?', null, null, 4),
  ('chemistry', 'reactivity-2-how-much-how-fast-how-far', 'Reactivity 2 — How Much, How Fast and How Far?', null, null, 5),
  ('chemistry', 'reactivity-3-mechanisms', 'Reactivity 3 — What are the Mechanisms of Chemical Change?', null, null, 6),
  ('biology', 'unity-and-diversity', 'Theme A — Unity and Diversity', null, null, 1),
  ('biology', 'form-and-function', 'Theme B — Form and Function', null, null, 2),
  ('biology', 'interaction-and-interdependence', 'Theme C — Interaction and Interdependence', null, null, 3),
  ('biology', 'continuity-and-change', 'Theme D — Continuity and Change', null, null, 4),
  ('economics', 'introduction-to-economics', 'Introduction to Economics', null, null, 1),
  ('economics', 'microeconomics', 'Microeconomics', null, null, 2),
  ('economics', 'macroeconomics', 'Macroeconomics', null, null, 3),
  ('economics', 'the-global-economy', 'The Global Economy', null, null, 4),
  ('global-politics', 'power-sovereignty-international-relations', 'Power, Sovereignty and International Relations', null, null, 1),
  ('global-politics', 'human-rights', 'Human Rights', null, null, 2),
  ('global-politics', 'development', 'Development', null, null, 3),
  ('global-politics', 'peace-and-conflict', 'Peace and Conflict', null, null, 4),
  ('psychology', 'biological-approach', 'Biological Approach to Behaviour', null, null, 1),
  ('psychology', 'cognitive-approach', 'Cognitive Approach to Behaviour', null, null, 2),
  ('psychology', 'sociocultural-approach', 'Sociocultural Approach to Behaviour', null, null, 3),
  ('psychology', 'options-and-research', 'Options and Research Methodology', null, null, 4),
  ('philosophy', 'core-theme-being-human', 'Core Theme — Being Human', null, null, 1),
  ('philosophy', 'optional-themes', 'Optional Themes', null, null, 2),
  ('philosophy', 'prescribed-text', 'Prescribed Text', null, null, 3),
  ('philosophy', 'hl-extension', 'HL Extension — Philosophy of Philosophy', null, 'HL', 4),
  ('world-religions', 'introduction-to-world-religions', 'Introduction to World Religions', null, null, 1),
  ('world-religions', 'in-depth-studies', 'In-depth Studies', null, null, 2)
) as t(subject_slug, slug, name, description, level_code, sort_order) on t.subject_slug = s.slug
on conflict (subject_id, slug) do update set
  name = excluded.name, description = excluded.description,
  level_code = excluded.level_code, sort_order = excluded.sort_order;

insert into public.topics (subject_id, theme_id, slug, name, description, level_code, sort_order)
select s.id, th.id, t.slug, t.name, t.description, t.level_code, t.sort_order
from public.subjects s
join (values
  ('math-aa', 'number-algebra', 'sequences-series', 'Sequences & Series', null, null, 1),
  ('math-aa', 'number-algebra', 'exponents-logarithms', 'Exponents & Logarithms', null, null, 2),
  ('math-aa', 'number-algebra', 'binomial-theorem', 'Binomial Theorem', null, null, 3),
  ('math-aa', 'number-algebra', 'proof', 'Proof', null, 'HL', 4),
  ('math-aa', 'number-algebra', 'complex-numbers', 'Complex Numbers', null, 'HL', 5),
  ('math-aa', 'functions', 'linear-quadratic', 'Linear & Quadratic Functions', null, null, 1),
  ('math-aa', 'functions', 'function-properties', 'Function Properties', null, null, 2),
  ('math-aa', 'functions', 'rational-exponential-log', 'Rational, Exponential & Log Functions', null, null, 3),
  ('math-aa', 'functions', 'transformations', 'Transformations of Graphs', null, null, 4),
  ('math-aa', 'geometry-trigonometry', 'triangle-trigonometry', 'Triangle Trigonometry', null, null, 1),
  ('math-aa', 'geometry-trigonometry', 'circular-functions', 'Circular Functions', null, null, 2),
  ('math-aa', 'geometry-trigonometry', 'trigonometric-identities', 'Trigonometric Identities & Equations', null, null, 3),
  ('math-aa', 'geometry-trigonometry', 'vectors', 'Vectors', null, 'HL', 4),
  ('math-aa', 'statistics-probability', 'descriptive-statistics', 'Descriptive Statistics', null, null, 1),
  ('math-aa', 'statistics-probability', 'probability', 'Probability', null, null, 2),
  ('math-aa', 'statistics-probability', 'distributions', 'Probability Distributions', null, null, 3),
  ('math-aa', 'statistics-probability', 'bivariate-statistics', 'Bivariate Statistics', null, null, 4),
  ('math-aa', 'calculus', 'limits', 'Limits', null, null, 1),
  ('math-aa', 'calculus', 'differentiation', 'Differentiation', null, null, 2),
  ('math-aa', 'calculus', 'applications-of-derivatives', 'Applications of Derivatives', null, null, 3),
  ('math-aa', 'calculus', 'integration', 'Integration', null, null, 4),
  ('math-aa', 'calculus', 'differential-equations', 'Differential Equations', null, 'HL', 5),
  ('math-ai', 'number-algebra', 'approximation', 'Approximation & Error', null, null, 1),
  ('math-ai', 'number-algebra', 'sequences-finance', 'Sequences & Financial Mathematics', null, null, 2),
  ('math-ai', 'number-algebra', 'matrices', 'Matrices', null, 'HL', 3),
  ('math-ai', 'functions', 'linear-models', 'Linear Models', null, null, 1),
  ('math-ai', 'functions', 'nonlinear-models', 'Non-linear Models', null, null, 2),
  ('math-ai', 'functions', 'modelling-skills', 'Modelling Skills', null, null, 3),
  ('math-ai', 'geometry-trigonometry', 'geometry-3d', '3D Geometry & Measurement', null, null, 1),
  ('math-ai', 'geometry-trigonometry', 'trigonometry-applications', 'Applied Trigonometry', null, null, 2),
  ('math-ai', 'geometry-trigonometry', 'voronoi-graph-theory', 'Voronoi Diagrams & Graph Theory', null, null, 3),
  ('math-ai', 'statistics-probability', 'data-collection', 'Data Collection & Presentation', null, null, 1),
  ('math-ai', 'statistics-probability', 'correlation-regression', 'Correlation & Regression', null, null, 2),
  ('math-ai', 'statistics-probability', 'probability-distributions', 'Probability & Distributions', null, null, 3),
  ('math-ai', 'statistics-probability', 'hypothesis-testing', 'Statistical Tests', null, null, 4),
  ('math-ai', 'calculus', 'differentiation', 'Differentiation', null, null, 1),
  ('math-ai', 'calculus', 'integration', 'Integration', null, null, 2),
  ('math-ai', 'calculus', 'differential-equations', 'Differential Equations & Slope Fields', null, 'HL', 3),
  ('math-ai', 'discrete-mathematics', 'graphs-networks', 'Graphs & Networks', null, 'HL', 1),
  ('math-ai', 'discrete-mathematics', 'markov-chains', 'Markov Chains', null, 'HL', 2),
  ('physics', 'space-time-motion', 'kinematics', 'Kinematics', null, null, 1),
  ('physics', 'space-time-motion', 'forces-motion', 'Forces and Motion', null, null, 2),
  ('physics', 'space-time-motion', 'work-energy-power', 'Work, Energy and Power', null, null, 3),
  ('physics', 'space-time-motion', 'momentum-impulse', 'Momentum and Impulse', null, null, 4),
  ('physics', 'particulate-nature-of-matter', 'thermal-physics', 'Thermal Physics', null, null, 1),
  ('physics', 'particulate-nature-of-matter', 'ideal-gases', 'Ideal Gases', null, null, 2),
  ('physics', 'particulate-nature-of-matter', 'nuclear-structure', 'Nuclear Structure', null, null, 3),
  ('physics', 'particulate-nature-of-matter', 'radioactivity', 'Radioactivity', null, null, 4),
  ('physics', 'wave-behaviour', 'oscillations', 'Oscillations', null, null, 1),
  ('physics', 'wave-behaviour', 'wave-model', 'Wave Model', null, null, 2),
  ('physics', 'wave-behaviour', 'wave-phenomena', 'Wave Phenomena', null, null, 3),
  ('physics', 'wave-behaviour', 'standing-waves', 'Standing Waves', null, null, 4),
  ('physics', 'fields', 'gravitational-fields', 'Gravitational Fields', null, null, 1),
  ('physics', 'fields', 'electric-fields', 'Electric Fields', null, null, 2),
  ('physics', 'fields', 'magnetic-fields', 'Magnetic Fields', null, null, 3),
  ('physics', 'fields', 'electromagnetic-induction', 'Electromagnetic Induction', null, null, 4),
  ('physics', 'nuclear-quantum-physics', 'quantum-physics', 'Quantum Physics', null, null, 1),
  ('physics', 'nuclear-quantum-physics', 'nuclear-physics', 'Nuclear Physics', null, null, 2),
  ('physics', 'nuclear-quantum-physics', 'particle-physics', 'Particle Physics', null, null, 3),
  ('chemistry', 'structure-1-particulate-nature', 'introduction-to-particulate-nature', 'Introduction to the Particulate Nature of Matter', null, null, 1),
  ('chemistry', 'structure-1-particulate-nature', 'the-nuclear-atom', 'The Nuclear Atom', null, null, 2),
  ('chemistry', 'structure-1-particulate-nature', 'electron-configurations', 'Electron Configurations', null, null, 3),
  ('chemistry', 'structure-1-particulate-nature', 'counting-particles-by-mass', 'Counting Particles by Mass: the Mole', null, null, 4),
  ('chemistry', 'structure-2-bonding', 'ionic-model', 'The Ionic Model', null, null, 1),
  ('chemistry', 'structure-2-bonding', 'covalent-model', 'The Covalent Model', null, null, 2),
  ('chemistry', 'structure-2-bonding', 'metallic-model', 'The Metallic Model', null, null, 3),
  ('chemistry', 'structure-2-bonding', 'from-models-to-materials', 'From Models to Materials', null, null, 4),
  ('chemistry', 'structure-3-classification', 'periodic-table', 'The Periodic Table: Classification of Elements', null, null, 1),
  ('chemistry', 'structure-3-classification', 'functional-groups', 'Functional Groups: Classification of Organic Compounds', null, null, 2),
  ('chemistry', 'reactivity-1-what-drives-reactions', 'measuring-enthalpy-changes', 'Measuring Enthalpy Changes', null, null, 1),
  ('chemistry', 'reactivity-1-what-drives-reactions', 'energy-cycles', 'Energy Cycles in Reactions', null, null, 2),
  ('chemistry', 'reactivity-1-what-drives-reactions', 'energy-from-fuels', 'Energy from Fuels', null, null, 3),
  ('chemistry', 'reactivity-1-what-drives-reactions', 'entropy-spontaneity', 'Entropy and Spontaneity', null, null, 4),
  ('chemistry', 'reactivity-2-how-much-how-fast-how-far', 'amount-of-chemical-change', 'How Much? The Amount of Chemical Change', null, null, 1),
  ('chemistry', 'reactivity-2-how-much-how-fast-how-far', 'rate-of-reaction', 'How Fast? The Rate of Chemical Change', null, null, 2),
  ('chemistry', 'reactivity-2-how-much-how-fast-how-far', 'extent-of-reaction', 'How Far? The Extent of Chemical Change', null, null, 3),
  ('chemistry', 'reactivity-3-mechanisms', 'proton-transfer', 'Proton Transfer Reactions', null, null, 1),
  ('chemistry', 'reactivity-3-mechanisms', 'electron-transfer', 'Electron Transfer Reactions', null, null, 2),
  ('chemistry', 'reactivity-3-mechanisms', 'electron-sharing', 'Electron Sharing Reactions', null, null, 3),
  ('chemistry', 'reactivity-3-mechanisms', 'electron-pair-sharing', 'Electron-pair Sharing Reactions', null, null, 4),
  ('biology', 'unity-and-diversity', 'molecules', 'Molecules', null, null, 1),
  ('biology', 'unity-and-diversity', 'cells', 'Cells', null, null, 2),
  ('biology', 'unity-and-diversity', 'organisms', 'Organisms', null, null, 3),
  ('biology', 'unity-and-diversity', 'ecosystems', 'Ecosystems', null, null, 4),
  ('biology', 'form-and-function', 'molecules-form-function', 'Molecules', null, null, 1),
  ('biology', 'form-and-function', 'cells-form-function', 'Cells', null, null, 2),
  ('biology', 'form-and-function', 'organisms-form-function', 'Organisms', null, null, 3),
  ('biology', 'form-and-function', 'ecosystems-form-function', 'Ecosystems', null, null, 4),
  ('biology', 'interaction-and-interdependence', 'molecules-interaction', 'Molecules', null, null, 1),
  ('biology', 'interaction-and-interdependence', 'cells-interaction', 'Cells', null, null, 2),
  ('biology', 'interaction-and-interdependence', 'organisms-interaction', 'Organisms', null, null, 3),
  ('biology', 'interaction-and-interdependence', 'ecosystems-interaction', 'Ecosystems', null, null, 4),
  ('biology', 'continuity-and-change', 'molecules-continuity', 'Molecules', null, null, 1),
  ('biology', 'continuity-and-change', 'cells-continuity', 'Cells', null, null, 2),
  ('biology', 'continuity-and-change', 'organisms-continuity', 'Organisms', null, null, 3),
  ('biology', 'continuity-and-change', 'ecosystems-continuity', 'Ecosystems', null, null, 4),
  ('economics', 'introduction-to-economics', 'what-is-economics', 'What is Economics?', null, null, 1),
  ('economics', 'introduction-to-economics', 'how-economists-work', 'How Do Economists Approach the World?', null, null, 2),
  ('economics', 'microeconomics', 'demand-supply', 'Demand and Supply', null, null, 1),
  ('economics', 'microeconomics', 'elasticity', 'Elasticities', null, null, 2),
  ('economics', 'microeconomics', 'government-intervention', 'Government Intervention', null, null, 3),
  ('economics', 'microeconomics', 'market-failure', 'Market Failure', null, null, 4),
  ('economics', 'microeconomics', 'theory-of-the-firm', 'Theory of the Firm', null, 'HL', 5),
  ('economics', 'macroeconomics', 'measuring-economic-activity', 'Measuring Economic Activity', null, null, 1),
  ('economics', 'macroeconomics', 'ad-as', 'Aggregate Demand and Supply', null, null, 2),
  ('economics', 'macroeconomics', 'macro-objectives', 'Macroeconomic Objectives', null, null, 3),
  ('economics', 'macroeconomics', 'demand-supply-side-policies', 'Demand and Supply-side Policies', null, null, 4),
  ('economics', 'the-global-economy', 'international-trade', 'International Trade', null, null, 1),
  ('economics', 'the-global-economy', 'exchange-rates', 'Exchange Rates & the Balance of Payments', null, null, 2),
  ('economics', 'the-global-economy', 'economic-integration', 'Economic Integration', null, null, 3),
  ('economics', 'the-global-economy', 'economic-development', 'Economic Development', null, null, 4),
  ('global-politics', 'power-sovereignty-international-relations', 'nature-of-power', 'The Nature of Power', null, null, 1),
  ('global-politics', 'power-sovereignty-international-relations', 'sovereignty-and-the-state', 'Sovereignty and the State', null, null, 2),
  ('global-politics', 'power-sovereignty-international-relations', 'global-governance', 'Global Governance', null, null, 3),
  ('global-politics', 'human-rights', 'nature-of-human-rights', 'The Nature of Human Rights', null, null, 1),
  ('global-politics', 'human-rights', 'protecting-human-rights', 'Codification and Protection', null, null, 2),
  ('global-politics', 'human-rights', 'human-rights-debates', 'Contemporary Debates', null, null, 3),
  ('global-politics', 'development', 'contested-meanings-of-development', 'Contested Meanings of Development', null, null, 1),
  ('global-politics', 'development', 'factors-affecting-development', 'Factors Affecting Development', null, null, 2),
  ('global-politics', 'development', 'pathways-to-development', 'Pathways to Development', null, null, 3),
  ('global-politics', 'peace-and-conflict', 'conceptualising-peace-conflict', 'Conceptualising Peace and Conflict', null, null, 1),
  ('global-politics', 'peace-and-conflict', 'causes-and-parties', 'Causes and Parties to Conflict', null, null, 2),
  ('global-politics', 'peace-and-conflict', 'conflict-resolution', 'Conflict Resolution & Peacebuilding', null, null, 3),
  ('psychology', 'biological-approach', 'brain-and-behaviour', 'The Brain and Behaviour', null, null, 1),
  ('psychology', 'biological-approach', 'hormones-and-pheromones', 'Hormones and Pheromones', null, null, 2),
  ('psychology', 'biological-approach', 'genetics-and-behaviour', 'Genetics and Behaviour', null, null, 3),
  ('psychology', 'cognitive-approach', 'models-of-memory', 'Cognitive Processing', null, null, 1),
  ('psychology', 'cognitive-approach', 'reliability-of-cognition', 'Reliability of Cognitive Processes', null, null, 2),
  ('psychology', 'cognitive-approach', 'emotion-and-cognition', 'Emotion and Cognition', null, null, 3),
  ('psychology', 'sociocultural-approach', 'individual-and-group', 'The Individual and the Group', null, null, 1),
  ('psychology', 'sociocultural-approach', 'cultural-origins', 'Cultural Origins of Behaviour', null, null, 2),
  ('psychology', 'sociocultural-approach', 'cultural-influences', 'Cultural Influences on Behaviour', null, null, 3),
  ('psychology', 'options-and-research', 'abnormal-psychology', 'Abnormal Psychology', null, null, 1),
  ('psychology', 'options-and-research', 'developmental-psychology', 'Developmental Psychology', null, null, 2),
  ('psychology', 'options-and-research', 'health-psychology', 'Health Psychology', null, null, 3),
  ('psychology', 'options-and-research', 'human-relationships', 'Human Relationships', null, null, 4),
  ('psychology', 'options-and-research', 'research-methodology', 'Research Methodology', null, null, 5),
  ('philosophy', 'core-theme-being-human', 'human-nature', 'What is a Human Being?', null, null, 1),
  ('philosophy', 'core-theme-being-human', 'self-and-others', 'The Self and Others', null, null, 2),
  ('philosophy', 'optional-themes', 'ethics', 'Ethics', null, null, 1),
  ('philosophy', 'optional-themes', 'epistemology', 'Epistemology', null, null, 2),
  ('philosophy', 'optional-themes', 'aesthetics', 'Aesthetics', null, null, 3),
  ('philosophy', 'optional-themes', 'philosophy-of-religion', 'Philosophy of Religion', null, null, 4),
  ('philosophy', 'optional-themes', 'political-philosophy', 'Political Philosophy', null, null, 5),
  ('philosophy', 'optional-themes', 'philosophy-of-science', 'Philosophy of Science', null, null, 6),
  ('philosophy', 'prescribed-text', 'reading-the-text', 'Reading the Prescribed Text', null, null, 1),
  ('philosophy', 'hl-extension', 'doing-philosophy', 'Doing Philosophy', null, 'HL', 1),
  ('world-religions', 'introduction-to-world-religions', 'hinduism', 'Hinduism', null, null, 1),
  ('world-religions', 'introduction-to-world-religions', 'buddhism', 'Buddhism', null, null, 2),
  ('world-religions', 'introduction-to-world-religions', 'sikhism', 'Sikhism', null, null, 3),
  ('world-religions', 'introduction-to-world-religions', 'judaism', 'Judaism', null, null, 4),
  ('world-religions', 'introduction-to-world-religions', 'christianity', 'Christianity', null, null, 5),
  ('world-religions', 'introduction-to-world-religions', 'islam', 'Islam', null, null, 6),
  ('world-religions', 'introduction-to-world-religions', 'jainism', 'Jainism', null, null, 7),
  ('world-religions', 'introduction-to-world-religions', 'taoism', 'Taoism', null, null, 8),
  ('world-religions', 'in-depth-studies', 'rituals-and-practices', 'Rituals and Practices', null, null, 1),
  ('world-religions', 'in-depth-studies', 'religious-experience', 'Religious Experience', null, null, 2),
  ('world-religions', 'in-depth-studies', 'ethics-and-religion', 'Religion and Ethics', null, null, 3),
  ('world-religions', 'in-depth-studies', 'religion-and-society', 'Religion and Society', null, null, 4)
) as t(subject_slug, theme_slug, slug, name, description, level_code, sort_order) on t.subject_slug = s.slug
join public.themes th on th.subject_id = s.id and th.slug = t.theme_slug
on conflict (subject_id, slug) do update set
  theme_id = excluded.theme_id, name = excluded.name,
  description = excluded.description, level_code = excluded.level_code,
  sort_order = excluded.sort_order;

insert into public.subtopics (topic_id, slug, name, sort_order)
select tp.id, st.slug, st.name, st.sort_order
from public.subjects s
join (values
  ('math-aa', 'sequences-series', 'arithmetic-sequences', 'Arithmetic sequences', 1),
  ('math-aa', 'sequences-series', 'geometric-sequences', 'Geometric sequences', 2),
  ('math-aa', 'sequences-series', 'sigma-notation', 'Sigma notation', 3),
  ('math-aa', 'sequences-series', 'compound-interest', 'Compound interest', 4),
  ('math-aa', 'exponents-logarithms', 'laws-of-exponents', 'Laws of exponents', 1),
  ('math-aa', 'exponents-logarithms', 'laws-of-logarithms', 'Laws of logarithms', 2),
  ('math-aa', 'exponents-logarithms', 'exponential-equations', 'Exponential equations', 3),
  ('math-aa', 'binomial-theorem', 'binomial-expansion', 'Binomial expansion', 1),
  ('math-aa', 'binomial-theorem', 'general-term', 'General term', 2),
  ('math-aa', 'proof', 'proof-by-deduction', 'Proof by deduction', 1),
  ('math-aa', 'proof', 'proof-by-induction', 'Proof by induction', 2),
  ('math-aa', 'proof', 'proof-by-contradiction', 'Proof by contradiction', 3),
  ('math-aa', 'complex-numbers', 'cartesian-form', 'Cartesian form', 1),
  ('math-aa', 'complex-numbers', 'polar-form', 'Polar form', 2),
  ('math-aa', 'complex-numbers', 'de-moivres-theorem', 'De Moivre''s theorem', 3),
  ('math-aa', 'linear-quadratic', 'straight-lines', 'Straight lines', 1),
  ('math-aa', 'linear-quadratic', 'quadratic-graphs', 'Quadratic graphs', 2),
  ('math-aa', 'linear-quadratic', 'discriminant', 'Discriminant', 3),
  ('math-aa', 'function-properties', 'domain-and-range', 'Domain and range', 1),
  ('math-aa', 'function-properties', 'composite-functions', 'Composite functions', 2),
  ('math-aa', 'function-properties', 'inverse-functions', 'Inverse functions', 3),
  ('math-aa', 'rational-exponential-log', 'rational-functions', 'Rational functions', 1),
  ('math-aa', 'rational-exponential-log', 'exponential-models', 'Exponential models', 2),
  ('math-aa', 'rational-exponential-log', 'logarithmic-graphs', 'Logarithmic graphs', 3),
  ('math-aa', 'transformations', 'translations', 'Translations', 1),
  ('math-aa', 'transformations', 'stretches', 'Stretches', 2),
  ('math-aa', 'transformations', 'reflections', 'Reflections', 3),
  ('math-aa', 'triangle-trigonometry', 'sine-rule', 'Sine rule', 1),
  ('math-aa', 'triangle-trigonometry', 'cosine-rule', 'Cosine rule', 2),
  ('math-aa', 'triangle-trigonometry', 'area-of-a-triangle', 'Area of a triangle', 3),
  ('math-aa', 'circular-functions', 'radians', 'Radians', 1),
  ('math-aa', 'circular-functions', 'unit-circle', 'Unit circle', 2),
  ('math-aa', 'circular-functions', 'trigonometric-graphs', 'Trigonometric graphs', 3),
  ('math-aa', 'trigonometric-identities', 'pythagorean-identities', 'Pythagorean identities', 1),
  ('math-aa', 'trigonometric-identities', 'double-angle-formulae', 'Double angle formulae', 2),
  ('math-aa', 'trigonometric-identities', 'solving-equations', 'Solving equations', 3),
  ('math-aa', 'vectors', 'vector-algebra', 'Vector algebra', 1),
  ('math-aa', 'vectors', 'scalar-product', 'Scalar product', 2),
  ('math-aa', 'vectors', 'vector-product', 'Vector product', 3),
  ('math-aa', 'vectors', 'lines-and-planes', 'Lines and planes', 4),
  ('math-aa', 'descriptive-statistics', 'measures-of-central-tendency', 'Measures of central tendency', 1),
  ('math-aa', 'descriptive-statistics', 'measures-of-dispersion', 'Measures of dispersion', 2),
  ('math-aa', 'descriptive-statistics', 'box-plots', 'Box plots', 3),
  ('math-aa', 'probability', 'combined-events', 'Combined events', 1),
  ('math-aa', 'probability', 'conditional-probability', 'Conditional probability', 2),
  ('math-aa', 'probability', 'independence', 'Independence', 3),
  ('math-aa', 'distributions', 'discrete-random-variables', 'Discrete random variables', 1),
  ('math-aa', 'distributions', 'binomial-distribution', 'Binomial distribution', 2),
  ('math-aa', 'distributions', 'normal-distribution', 'Normal distribution', 3),
  ('math-aa', 'bivariate-statistics', 'correlation', 'Correlation', 1),
  ('math-aa', 'bivariate-statistics', 'regression', 'Regression', 2),
  ('math-aa', 'limits', 'limits-from-graphs', 'Limits from graphs', 1),
  ('math-aa', 'limits', 'limits-and-continuity', 'Limits and continuity', 2),
  ('math-aa', 'limits', 'lh-pitals-rule', 'L''Hôpital''s rule', 3),
  ('math-aa', 'differentiation', 'first-principles', 'First principles', 1),
  ('math-aa', 'differentiation', 'chain-rule', 'Chain rule', 2),
  ('math-aa', 'differentiation', 'product-and-quotient-rules', 'Product and quotient rules', 3),
  ('math-aa', 'differentiation', 'implicit-differentiation', 'Implicit differentiation', 4),
  ('math-aa', 'applications-of-derivatives', 'tangents-and-normals', 'Tangents and normals', 1),
  ('math-aa', 'applications-of-derivatives', 'stationary-points', 'Stationary points', 2),
  ('math-aa', 'applications-of-derivatives', 'optimisation', 'Optimisation', 3),
  ('math-aa', 'applications-of-derivatives', 'kinematics', 'Kinematics', 4),
  ('math-aa', 'integration', 'indefinite-integrals', 'Indefinite integrals', 1),
  ('math-aa', 'integration', 'definite-integrals', 'Definite integrals', 2),
  ('math-aa', 'integration', 'integration-by-substitution', 'Integration by substitution', 3),
  ('math-aa', 'integration', 'integration-by-parts', 'Integration by parts', 4),
  ('math-aa', 'differential-equations', 'separation-of-variables', 'Separation of variables', 1),
  ('math-aa', 'differential-equations', 'eulers-method', 'Euler''s method', 2),
  ('math-ai', 'approximation', 'rounding-and-significant-figures', 'Rounding and significant figures', 1),
  ('math-ai', 'approximation', 'percentage-error', 'Percentage error', 2),
  ('math-ai', 'approximation', 'standard-form', 'Standard form', 3),
  ('math-ai', 'sequences-finance', 'arithmetic-and-geometric-sequences', 'Arithmetic and geometric sequences', 1),
  ('math-ai', 'sequences-finance', 'compound-interest', 'Compound interest', 2),
  ('math-ai', 'sequences-finance', 'amortisation-and-annuities', 'Amortisation and annuities', 3),
  ('math-ai', 'matrices', 'matrix-operations', 'Matrix operations', 1),
  ('math-ai', 'matrices', 'determinants-and-inverses', 'Determinants and inverses', 2),
  ('math-ai', 'matrices', 'eigenvalues-and-eigenvectors', 'Eigenvalues and eigenvectors', 3),
  ('math-ai', 'linear-models', 'gradient-and-intercept', 'Gradient and intercept', 1),
  ('math-ai', 'linear-models', 'piecewise-models', 'Piecewise models', 2),
  ('math-ai', 'nonlinear-models', 'quadratic-models', 'Quadratic models', 1),
  ('math-ai', 'nonlinear-models', 'exponential-models', 'Exponential models', 2),
  ('math-ai', 'nonlinear-models', 'logistic-models', 'Logistic models', 3),
  ('math-ai', 'modelling-skills', 'choosing-a-model', 'Choosing a model', 1),
  ('math-ai', 'modelling-skills', 'fitting-and-interpreting', 'Fitting and interpreting', 2),
  ('math-ai', 'modelling-skills', 'evaluating-a-model', 'Evaluating a model', 3),
  ('math-ai', 'geometry-3d', 'volume-and-surface-area', 'Volume and surface area', 1),
  ('math-ai', 'geometry-3d', 'angles-in-3d-solids', 'Angles in 3D solids', 2),
  ('math-ai', 'trigonometry-applications', 'sine-and-cosine-rules', 'Sine and cosine rules', 1),
  ('math-ai', 'trigonometry-applications', 'bearings', 'Bearings', 2),
  ('math-ai', 'trigonometry-applications', 'radians-and-arcs', 'Radians and arcs', 3),
  ('math-ai', 'voronoi-graph-theory', 'voronoi-diagrams', 'Voronoi diagrams', 1),
  ('math-ai', 'voronoi-graph-theory', 'adjacency-matrices', 'Adjacency matrices', 2),
  ('math-ai', 'voronoi-graph-theory', 'shortest-path-algorithms', 'Shortest path algorithms', 3),
  ('math-ai', 'data-collection', 'sampling-techniques', 'Sampling techniques', 1),
  ('math-ai', 'data-collection', 'frequency-tables', 'Frequency tables', 2),
  ('math-ai', 'data-collection', 'outliers', 'Outliers', 3),
  ('math-ai', 'correlation-regression', 'pearsons-r', 'Pearson''s r', 1),
  ('math-ai', 'correlation-regression', 'spearmans-rank', 'Spearman''s rank', 2),
  ('math-ai', 'correlation-regression', 'least-squares-regression', 'Least squares regression', 3),
  ('math-ai', 'probability-distributions', 'binomial-distribution', 'Binomial distribution', 1),
  ('math-ai', 'probability-distributions', 'normal-distribution', 'Normal distribution', 2),
  ('math-ai', 'probability-distributions', 'expected-value', 'Expected value', 3),
  ('math-ai', 'hypothesis-testing', 'chi-squared-test', 'Chi-squared test', 1),
  ('math-ai', 'hypothesis-testing', 't-test', 't-test', 2),
  ('math-ai', 'hypothesis-testing', 'validity-of-tests', 'Validity of tests', 3),
  ('math-ai', 'differentiation', 'rates-of-change', 'Rates of change', 1),
  ('math-ai', 'differentiation', 'tangents', 'Tangents', 2),
  ('math-ai', 'differentiation', 'optimisation', 'Optimisation', 3),
  ('math-ai', 'integration', 'areas-under-curves', 'Areas under curves', 1),
  ('math-ai', 'integration', 'trapezoidal-rule', 'Trapezoidal rule', 2),
  ('math-ai', 'integration', 'kinematics', 'Kinematics', 3),
  ('math-ai', 'differential-equations', 'slope-fields', 'Slope fields', 1),
  ('math-ai', 'differential-equations', 'eulers-method', 'Euler''s method', 2),
  ('math-ai', 'differential-equations', 'coupled-systems', 'Coupled systems', 3),
  ('math-ai', 'graphs-networks', 'minimum-spanning-trees', 'Minimum spanning trees', 1),
  ('math-ai', 'graphs-networks', 'chinese-postman-problem', 'Chinese postman problem', 2),
  ('math-ai', 'graphs-networks', 'travelling-salesman-problem', 'Travelling salesman problem', 3),
  ('math-ai', 'markov-chains', 'transition-matrices', 'Transition matrices', 1),
  ('math-ai', 'markov-chains', 'steady-states', 'Steady states', 2),
  ('physics', 'kinematics', 'displacement-and-velocity', 'Displacement and velocity', 1),
  ('physics', 'kinematics', 'uniform-acceleration', 'Uniform acceleration', 2),
  ('physics', 'kinematics', 'projectile-motion', 'Projectile motion', 3),
  ('physics', 'kinematics', 'graphs-of-motion', 'Graphs of motion', 4),
  ('physics', 'forces-motion', 'newtons-laws', 'Newton''s laws', 1),
  ('physics', 'forces-motion', 'friction', 'Friction', 2),
  ('physics', 'forces-motion', 'circular-motion', 'Circular motion', 3),
  ('physics', 'forces-motion', 'equilibrium', 'Equilibrium', 4),
  ('physics', 'work-energy-power', 'work-done', 'Work done', 1),
  ('physics', 'work-energy-power', 'conservation-of-energy', 'Conservation of energy', 2),
  ('physics', 'work-energy-power', 'efficiency-and-power', 'Efficiency and power', 3),
  ('physics', 'momentum-impulse', 'conservation-of-momentum', 'Conservation of momentum', 1),
  ('physics', 'momentum-impulse', 'impulse', 'Impulse', 2),
  ('physics', 'momentum-impulse', 'collisions', 'Collisions', 3),
  ('physics', 'thermal-physics', 'temperature-and-internal-energy', 'Temperature and internal energy', 1),
  ('physics', 'thermal-physics', 'specific-heat-capacity', 'Specific heat capacity', 2),
  ('physics', 'thermal-physics', 'latent-heat', 'Latent heat', 3),
  ('physics', 'ideal-gases', 'gas-laws', 'Gas laws', 1),
  ('physics', 'ideal-gases', 'kinetic-model', 'Kinetic model', 2),
  ('physics', 'ideal-gases', 'ideal-gas-equation', 'Ideal gas equation', 3),
  ('physics', 'nuclear-structure', 'isotopes', 'Isotopes', 1),
  ('physics', 'nuclear-structure', 'mass-defect-and-binding-energy', 'Mass defect and binding energy', 2),
  ('physics', 'radioactivity', 'types-of-decay', 'Types of decay', 1),
  ('physics', 'radioactivity', 'half-life', 'Half-life', 2),
  ('physics', 'radioactivity', 'nuclear-equations', 'Nuclear equations', 3),
  ('physics', 'oscillations', 'simple-harmonic-motion', 'Simple harmonic motion', 1),
  ('physics', 'oscillations', 'energy-in-shm', 'Energy in SHM', 2),
  ('physics', 'oscillations', 'damping', 'Damping', 3),
  ('physics', 'wave-model', 'wave-characteristics', 'Wave characteristics', 1),
  ('physics', 'wave-model', 'transverse-and-longitudinal-waves', 'Transverse and longitudinal waves', 2),
  ('physics', 'wave-model', 'wave-speed', 'Wave speed', 3),
  ('physics', 'wave-phenomena', 'reflection-and-refraction', 'Reflection and refraction', 1),
  ('physics', 'wave-phenomena', 'diffraction', 'Diffraction', 2),
  ('physics', 'wave-phenomena', 'interference', 'Interference', 3),
  ('physics', 'wave-phenomena', 'doppler-effect', 'Doppler effect', 4),
  ('physics', 'standing-waves', 'nodes-and-antinodes', 'Nodes and antinodes', 1),
  ('physics', 'standing-waves', 'harmonics-in-strings-and-pipes', 'Harmonics in strings and pipes', 2),
  ('physics', 'standing-waves', 'resonance', 'Resonance', 3),
  ('physics', 'gravitational-fields', 'newtons-law-of-gravitation', 'Newton''s law of gravitation', 1),
  ('physics', 'gravitational-fields', 'field-strength', 'Field strength', 2),
  ('physics', 'gravitational-fields', 'orbital-motion', 'Orbital motion', 3),
  ('physics', 'gravitational-fields', 'gravitational-potential', 'Gravitational potential', 4),
  ('physics', 'electric-fields', 'coulombs-law', 'Coulomb''s law', 1),
  ('physics', 'electric-fields', 'field-strength-and-potential', 'Field strength and potential', 2),
  ('physics', 'electric-fields', 'electric-circuits', 'Electric circuits', 3),
  ('physics', 'electric-fields', 'capacitance', 'Capacitance', 4),
  ('physics', 'magnetic-fields', 'magnetic-force-on-a-current', 'Magnetic force on a current', 1),
  ('physics', 'magnetic-fields', 'moving-charges', 'Moving charges', 2),
  ('physics', 'magnetic-fields', 'field-patterns', 'Field patterns', 3),
  ('physics', 'electromagnetic-induction', 'faradays-law', 'Faraday''s law', 1),
  ('physics', 'electromagnetic-induction', 'lenzs-law', 'Lenz''s law', 2),
  ('physics', 'electromagnetic-induction', 'transformers-and-ac', 'Transformers and AC', 3),
  ('physics', 'quantum-physics', 'photoelectric-effect', 'Photoelectric effect', 1),
  ('physics', 'quantum-physics', 'wave-particle-duality', 'Wave-particle duality', 2),
  ('physics', 'quantum-physics', 'atomic-spectra', 'Atomic spectra', 3),
  ('physics', 'nuclear-physics', 'fission-and-fusion', 'Fission and fusion', 1),
  ('physics', 'nuclear-physics', 'nuclear-energy', 'Nuclear energy', 2),
  ('physics', 'nuclear-physics', 'radioactive-decay-law', 'Radioactive decay law', 3),
  ('physics', 'particle-physics', 'standard-model', 'Standard model', 1),
  ('physics', 'particle-physics', 'quarks-and-leptons', 'Quarks and leptons', 2),
  ('physics', 'particle-physics', 'fundamental-interactions', 'Fundamental interactions', 3),
  ('chemistry', 'introduction-to-particulate-nature', 'states-of-matter', 'States of matter', 1),
  ('chemistry', 'introduction-to-particulate-nature', 'kinetic-molecular-theory', 'Kinetic molecular theory', 2),
  ('chemistry', 'the-nuclear-atom', 'subatomic-particles', 'Subatomic particles', 1),
  ('chemistry', 'the-nuclear-atom', 'isotopes', 'Isotopes', 2),
  ('chemistry', 'the-nuclear-atom', 'mass-spectrometry', 'Mass spectrometry', 3),
  ('chemistry', 'electron-configurations', 'emission-spectra', 'Emission spectra', 1),
  ('chemistry', 'electron-configurations', 'orbitals-and-sublevels', 'Orbitals and sublevels', 2),
  ('chemistry', 'electron-configurations', 'ionisation-energy', 'Ionisation energy', 3),
  ('chemistry', 'counting-particles-by-mass', 'the-mole', 'The mole', 1),
  ('chemistry', 'counting-particles-by-mass', 'empirical-and-molecular-formulae', 'Empirical and molecular formulae', 2),
  ('chemistry', 'counting-particles-by-mass', 'molar-concentration', 'Molar concentration', 3),
  ('chemistry', 'ionic-model', 'ion-formation', 'Ion formation', 1),
  ('chemistry', 'ionic-model', 'lattice-structure', 'Lattice structure', 2),
  ('chemistry', 'ionic-model', 'properties-of-ionic-compounds', 'Properties of ionic compounds', 3),
  ('chemistry', 'covalent-model', 'lewis-formulas', 'Lewis formulas', 1),
  ('chemistry', 'covalent-model', 'vsepr-and-shapes', 'VSEPR and shapes', 2),
  ('chemistry', 'covalent-model', 'intermolecular-forces', 'Intermolecular forces', 3),
  ('chemistry', 'covalent-model', 'giant-covalent-structures', 'Giant covalent structures', 4),
  ('chemistry', 'metallic-model', 'metallic-bonding', 'Metallic bonding', 1),
  ('chemistry', 'metallic-model', 'alloys', 'Alloys', 2),
  ('chemistry', 'from-models-to-materials', 'bonding-triangle', 'Bonding triangle', 1),
  ('chemistry', 'from-models-to-materials', 'polymers-and-composites', 'Polymers and composites', 2),
  ('chemistry', 'periodic-table', 'periodicity', 'Periodicity', 1),
  ('chemistry', 'periodic-table', 'trends-in-properties', 'Trends in properties', 2),
  ('chemistry', 'periodic-table', 'transition-metals', 'Transition metals', 3),
  ('chemistry', 'functional-groups', 'homologous-series', 'Homologous series', 1),
  ('chemistry', 'functional-groups', 'nomenclature', 'Nomenclature', 2),
  ('chemistry', 'functional-groups', 'isomerism', 'Isomerism', 3),
  ('chemistry', 'functional-groups', 'spectroscopy', 'Spectroscopy', 4),
  ('chemistry', 'measuring-enthalpy-changes', 'exothermic-and-endothermic', 'Exothermic and endothermic', 1),
  ('chemistry', 'measuring-enthalpy-changes', 'calorimetry', 'Calorimetry', 2),
  ('chemistry', 'energy-cycles', 'hesss-law', 'Hess''s law', 1),
  ('chemistry', 'energy-cycles', 'bond-enthalpies', 'Bond enthalpies', 2),
  ('chemistry', 'energy-cycles', 'born-haber-cycles', 'Born-Haber cycles', 3),
  ('chemistry', 'energy-from-fuels', 'combustion', 'Combustion', 1),
  ('chemistry', 'energy-from-fuels', 'fuel-cells-and-biofuels', 'Fuel cells and biofuels', 2),
  ('chemistry', 'entropy-spontaneity', 'entropy-change', 'Entropy change', 1),
  ('chemistry', 'entropy-spontaneity', 'gibbs-energy', 'Gibbs energy', 2),
  ('chemistry', 'amount-of-chemical-change', 'reacting-masses', 'Reacting masses', 1),
  ('chemistry', 'amount-of-chemical-change', 'limiting-reactants', 'Limiting reactants', 2),
  ('chemistry', 'amount-of-chemical-change', 'percentage-yield', 'Percentage yield', 3),
  ('chemistry', 'rate-of-reaction', 'collision-theory', 'Collision theory', 1),
  ('chemistry', 'rate-of-reaction', 'rate-equations', 'Rate equations', 2),
  ('chemistry', 'rate-of-reaction', 'reaction-mechanisms', 'Reaction mechanisms', 3),
  ('chemistry', 'extent-of-reaction', 'dynamic-equilibrium', 'Dynamic equilibrium', 1),
  ('chemistry', 'extent-of-reaction', 'le-chateliers-principle', 'Le Chatelier''s principle', 2),
  ('chemistry', 'extent-of-reaction', 'equilibrium-constants', 'Equilibrium constants', 3),
  ('chemistry', 'proton-transfer', 'acids-and-bases', 'Acids and bases', 1),
  ('chemistry', 'proton-transfer', 'ph-and-kw', 'pH and Kw', 2),
  ('chemistry', 'proton-transfer', 'buffers-and-titrations', 'Buffers and titrations', 3),
  ('chemistry', 'electron-transfer', 'redox-equations', 'Redox equations', 1),
  ('chemistry', 'electron-transfer', 'electrochemical-cells', 'Electrochemical cells', 2),
  ('chemistry', 'electron-transfer', 'electrolysis', 'Electrolysis', 3),
  ('chemistry', 'electron-sharing', 'radical-substitution', 'Radical substitution', 1),
  ('chemistry', 'electron-pair-sharing', 'nucleophilic-substitution', 'Nucleophilic substitution', 1),
  ('chemistry', 'electron-pair-sharing', 'electrophilic-addition', 'Electrophilic addition', 2),
  ('chemistry', 'electron-pair-sharing', 'elimination', 'Elimination', 3),
  ('biology', 'molecules', 'water', 'Water', 1),
  ('biology', 'molecules', 'nucleic-acids', 'Nucleic acids', 2),
  ('biology', 'cells', 'origins-of-cells', 'Origins of cells', 1),
  ('biology', 'cells', 'cell-structure', 'Cell structure', 2),
  ('biology', 'cells', 'viruses', 'Viruses', 3),
  ('biology', 'organisms', 'diversity-of-organisms', 'Diversity of organisms', 1),
  ('biology', 'organisms', 'classification-and-cladistics', 'Classification and cladistics', 2),
  ('biology', 'ecosystems', 'evolution-and-speciation', 'Evolution and speciation', 1),
  ('biology', 'ecosystems', 'conservation-of-biodiversity', 'Conservation of biodiversity', 2),
  ('biology', 'molecules-form-function', 'carbohydrates-and-lipids', 'Carbohydrates and lipids', 1),
  ('biology', 'molecules-form-function', 'proteins', 'Proteins', 2),
  ('biology', 'cells-form-function', 'membranes-and-transport', 'Membranes and transport', 1),
  ('biology', 'cells-form-function', 'organelles-and-compartmentalisation', 'Organelles and compartmentalisation', 2),
  ('biology', 'cells-form-function', 'cell-specialisation', 'Cell specialisation', 3),
  ('biology', 'organisms-form-function', 'gas-exchange', 'Gas exchange', 1),
  ('biology', 'organisms-form-function', 'transport', 'Transport', 2),
  ('biology', 'organisms-form-function', 'muscle-and-motility', 'Muscle and motility', 3),
  ('biology', 'ecosystems-form-function', 'adaptation-to-environment', 'Adaptation to environment', 1),
  ('biology', 'ecosystems-form-function', 'ecological-niches', 'Ecological niches', 2),
  ('biology', 'molecules-interaction', 'enzymes-and-metabolism', 'Enzymes and metabolism', 1),
  ('biology', 'molecules-interaction', 'cell-respiration', 'Cell respiration', 2),
  ('biology', 'molecules-interaction', 'photosynthesis', 'Photosynthesis', 3),
  ('biology', 'cells-interaction', 'chemical-signalling', 'Chemical signalling', 1),
  ('biology', 'cells-interaction', 'neural-signalling', 'Neural signalling', 2),
  ('biology', 'organisms-interaction', 'integration-of-body-systems', 'Integration of body systems', 1),
  ('biology', 'organisms-interaction', 'defence-against-disease', 'Defence against disease', 2),
  ('biology', 'ecosystems-interaction', 'populations-and-communities', 'Populations and communities', 1),
  ('biology', 'ecosystems-interaction', 'transfers-of-energy-and-matter', 'Transfers of energy and matter', 2),
  ('biology', 'molecules-continuity', 'dna-replication', 'DNA replication', 1),
  ('biology', 'molecules-continuity', 'protein-synthesis', 'Protein synthesis', 2),
  ('biology', 'molecules-continuity', 'mutations-and-gene-editing', 'Mutations and gene editing', 3),
  ('biology', 'cells-continuity', 'cell-and-nuclear-division', 'Cell and nuclear division', 1),
  ('biology', 'cells-continuity', 'gene-expression', 'Gene expression', 2),
  ('biology', 'cells-continuity', 'water-potential', 'Water potential', 3),
  ('biology', 'organisms-continuity', 'reproduction', 'Reproduction', 1),
  ('biology', 'organisms-continuity', 'inheritance', 'Inheritance', 2),
  ('biology', 'organisms-continuity', 'homeostasis', 'Homeostasis', 3),
  ('biology', 'ecosystems-continuity', 'natural-selection', 'Natural selection', 1),
  ('biology', 'ecosystems-continuity', 'stability-and-change', 'Stability and change', 2),
  ('biology', 'ecosystems-continuity', 'climate-change', 'Climate change', 3),
  ('economics', 'what-is-economics', 'scarcity-and-choice', 'Scarcity and choice', 1),
  ('economics', 'what-is-economics', 'opportunity-cost', 'Opportunity cost', 2),
  ('economics', 'what-is-economics', 'economic-systems', 'Economic systems', 3),
  ('economics', 'how-economists-work', 'models-and-assumptions', 'Models and assumptions', 1),
  ('economics', 'how-economists-work', 'positive-and-normative-economics', 'Positive and normative economics', 2),
  ('economics', 'demand-supply', 'law-of-demand', 'Law of demand', 1),
  ('economics', 'demand-supply', 'law-of-supply', 'Law of supply', 2),
  ('economics', 'demand-supply', 'market-equilibrium', 'Market equilibrium', 3),
  ('economics', 'elasticity', 'price-elasticity-of-demand', 'Price elasticity of demand', 1),
  ('economics', 'elasticity', 'income-elasticity', 'Income elasticity', 2),
  ('economics', 'elasticity', 'price-elasticity-of-supply', 'Price elasticity of supply', 3),
  ('economics', 'government-intervention', 'indirect-taxes', 'Indirect taxes', 1),
  ('economics', 'government-intervention', 'subsidies', 'Subsidies', 2),
  ('economics', 'government-intervention', 'price-controls', 'Price controls', 3),
  ('economics', 'market-failure', 'externalities', 'Externalities', 1),
  ('economics', 'market-failure', 'public-goods', 'Public goods', 2),
  ('economics', 'market-failure', 'asymmetric-information', 'Asymmetric information', 3),
  ('economics', 'theory-of-the-firm', 'costs-and-revenues', 'Costs and revenues', 1),
  ('economics', 'theory-of-the-firm', 'perfect-competition', 'Perfect competition', 2),
  ('economics', 'theory-of-the-firm', 'monopoly-and-oligopoly', 'Monopoly and oligopoly', 3),
  ('economics', 'measuring-economic-activity', 'gdp-and-gni', 'GDP and GNI', 1),
  ('economics', 'measuring-economic-activity', 'the-business-cycle', 'The business cycle', 2),
  ('economics', 'measuring-economic-activity', 'alternative-measures', 'Alternative measures', 3),
  ('economics', 'ad-as', 'components-of-ad', 'Components of AD', 1),
  ('economics', 'ad-as', 'sras-and-lras', 'SRAS and LRAS', 2),
  ('economics', 'ad-as', 'equilibrium-output', 'Equilibrium output', 3),
  ('economics', 'macro-objectives', 'economic-growth', 'Economic growth', 1),
  ('economics', 'macro-objectives', 'unemployment', 'Unemployment', 2),
  ('economics', 'macro-objectives', 'inflation', 'Inflation', 3),
  ('economics', 'macro-objectives', 'income-distribution', 'Income distribution', 4),
  ('economics', 'demand-supply-side-policies', 'monetary-policy', 'Monetary policy', 1),
  ('economics', 'demand-supply-side-policies', 'fiscal-policy', 'Fiscal policy', 2),
  ('economics', 'demand-supply-side-policies', 'supply-side-policy', 'Supply-side policy', 3),
  ('economics', 'international-trade', 'benefits-of-trade', 'Benefits of trade', 1),
  ('economics', 'international-trade', 'protectionism', 'Protectionism', 2),
  ('economics', 'international-trade', 'trade-agreements', 'Trade agreements', 3),
  ('economics', 'exchange-rates', 'exchange-rate-systems', 'Exchange rate systems', 1),
  ('economics', 'exchange-rates', 'current-account', 'Current account', 2),
  ('economics', 'exchange-rates', 'marshall-lerner-and-the-j-curve', 'Marshall-Lerner and the J-curve', 3),
  ('economics', 'economic-integration', 'trading-blocs', 'Trading blocs', 1),
  ('economics', 'economic-integration', 'monetary-union', 'Monetary union', 2),
  ('economics', 'economic-integration', 'wto', 'WTO', 3),
  ('economics', 'economic-development', 'measuring-development', 'Measuring development', 1),
  ('economics', 'economic-development', 'barriers-to-development', 'Barriers to development', 2),
  ('economics', 'economic-development', 'strategies-for-development', 'Strategies for development', 3),
  ('global-politics', 'nature-of-power', 'types-of-power', 'Types of power', 1),
  ('global-politics', 'nature-of-power', 'legitimacy-and-authority', 'Legitimacy and authority', 2),
  ('global-politics', 'sovereignty-and-the-state', 'the-state-and-statehood', 'The state and statehood', 1),
  ('global-politics', 'sovereignty-and-the-state', 'challenges-to-sovereignty', 'Challenges to sovereignty', 2),
  ('global-politics', 'global-governance', 'intergovernmental-organisations', 'Intergovernmental organisations', 1),
  ('global-politics', 'global-governance', 'ngos-and-civil-society', 'NGOs and civil society', 2),
  ('global-politics', 'global-governance', 'treaties-and-international-law', 'Treaties and international law', 3),
  ('global-politics', 'nature-of-human-rights', 'universality-and-relativism', 'Universality and relativism', 1),
  ('global-politics', 'nature-of-human-rights', 'generations-of-rights', 'Generations of rights', 2),
  ('global-politics', 'protecting-human-rights', 'udhr-and-treaties', 'UDHR and treaties', 1),
  ('global-politics', 'protecting-human-rights', 'international-courts', 'International courts', 2),
  ('global-politics', 'protecting-human-rights', 'monitoring-and-enforcement', 'Monitoring and enforcement', 3),
  ('global-politics', 'human-rights-debates', 'rights-violations', 'Rights violations', 1),
  ('global-politics', 'human-rights-debates', 'humanitarian-intervention', 'Humanitarian intervention', 2),
  ('global-politics', 'human-rights-debates', 'culture-and-rights', 'Culture and rights', 3),
  ('global-politics', 'contested-meanings-of-development', 'definitions-of-development', 'Definitions of development', 1),
  ('global-politics', 'contested-meanings-of-development', 'measuring-development', 'Measuring development', 2),
  ('global-politics', 'factors-affecting-development', 'political-factors', 'Political factors', 1),
  ('global-politics', 'factors-affecting-development', 'economic-factors', 'Economic factors', 2),
  ('global-politics', 'factors-affecting-development', 'social-and-environmental-factors', 'Social and environmental factors', 3),
  ('global-politics', 'pathways-to-development', 'aid-and-trade', 'Aid and trade', 1),
  ('global-politics', 'pathways-to-development', 'sustainable-development', 'Sustainable development', 2),
  ('global-politics', 'pathways-to-development', 'debt-relief', 'Debt relief', 3),
  ('global-politics', 'conceptualising-peace-conflict', 'positive-and-negative-peace', 'Positive and negative peace', 1),
  ('global-politics', 'conceptualising-peace-conflict', 'types-of-violence', 'Types of violence', 2),
  ('global-politics', 'causes-and-parties', 'causes-of-conflict', 'Causes of conflict', 1),
  ('global-politics', 'causes-and-parties', 'state-and-non-state-actors', 'State and non-state actors', 2),
  ('global-politics', 'conflict-resolution', 'negotiation-and-mediation', 'Negotiation and mediation', 1),
  ('global-politics', 'conflict-resolution', 'peacekeeping', 'Peacekeeping', 2),
  ('global-politics', 'conflict-resolution', 'post-conflict-transformation', 'Post-conflict transformation', 3),
  ('psychology', 'brain-and-behaviour', 'localisation', 'Localisation', 1),
  ('psychology', 'brain-and-behaviour', 'neuroplasticity', 'Neuroplasticity', 2),
  ('psychology', 'brain-and-behaviour', 'neurotransmitters', 'Neurotransmitters', 3),
  ('psychology', 'hormones-and-pheromones', 'hormones-and-behaviour', 'Hormones and behaviour', 1),
  ('psychology', 'hormones-and-pheromones', 'pheromones', 'Pheromones', 2),
  ('psychology', 'genetics-and-behaviour', 'genes-and-behaviour', 'Genes and behaviour', 1),
  ('psychology', 'genetics-and-behaviour', 'evolutionary-explanations', 'Evolutionary explanations', 2),
  ('psychology', 'models-of-memory', 'models-of-memory', 'Models of memory', 1),
  ('psychology', 'models-of-memory', 'schema-theory', 'Schema theory', 2),
  ('psychology', 'models-of-memory', 'thinking-and-decision-making', 'Thinking and decision-making', 3),
  ('psychology', 'reliability-of-cognition', 'reconstructive-memory', 'Reconstructive memory', 1),
  ('psychology', 'reliability-of-cognition', 'biases-in-thinking', 'Biases in thinking', 2),
  ('psychology', 'emotion-and-cognition', 'flashbulb-memory', 'Flashbulb memory', 1),
  ('psychology', 'emotion-and-cognition', 'emotion-and-decision-making', 'Emotion and decision-making', 2),
  ('psychology', 'individual-and-group', 'social-identity-theory', 'Social identity theory', 1),
  ('psychology', 'individual-and-group', 'social-cognitive-theory', 'Social cognitive theory', 2),
  ('psychology', 'individual-and-group', 'stereotypes', 'Stereotypes', 3),
  ('psychology', 'cultural-origins', 'culture-and-cultural-dimensions', 'Culture and cultural dimensions', 1),
  ('psychology', 'cultural-origins', 'enculturation-and-acculturation', 'Enculturation and acculturation', 2),
  ('psychology', 'cultural-influences', 'globalisation-and-behaviour', 'Globalisation and behaviour', 1),
  ('psychology', 'abnormal-psychology', 'diagnosis', 'Diagnosis', 1),
  ('psychology', 'abnormal-psychology', 'aetiology', 'Aetiology', 2),
  ('psychology', 'abnormal-psychology', 'treatment', 'Treatment', 3),
  ('psychology', 'developmental-psychology', 'influences-on-development', 'Influences on development', 1),
  ('psychology', 'developmental-psychology', 'developing-an-identity', 'Developing an identity', 2),
  ('psychology', 'health-psychology', 'determinants-of-health', 'Determinants of health', 1),
  ('psychology', 'health-psychology', 'health-problems', 'Health problems', 2),
  ('psychology', 'health-psychology', 'promoting-health', 'Promoting health', 3),
  ('psychology', 'human-relationships', 'personal-relationships', 'Personal relationships', 1),
  ('psychology', 'human-relationships', 'group-dynamics', 'Group dynamics', 2),
  ('psychology', 'human-relationships', 'social-responsibility', 'Social responsibility', 3),
  ('psychology', 'research-methodology', 'quantitative-methods', 'Quantitative methods', 1),
  ('psychology', 'research-methodology', 'qualitative-methods', 'Qualitative methods', 2),
  ('psychology', 'research-methodology', 'ethics-in-research', 'Ethics in research', 3),
  ('philosophy', 'human-nature', 'human-nature', 'Human nature', 1),
  ('philosophy', 'human-nature', 'personhood', 'Personhood', 2),
  ('philosophy', 'human-nature', 'mind-and-body', 'Mind and body', 3),
  ('philosophy', 'self-and-others', 'personal-identity', 'Personal identity', 1),
  ('philosophy', 'self-and-others', 'freedom-and-determinism', 'Freedom and determinism', 2),
  ('philosophy', 'self-and-others', 'human-relationships', 'Human relationships', 3),
  ('philosophy', 'ethics', 'normative-ethics', 'Normative ethics', 1),
  ('philosophy', 'ethics', 'metaethics', 'Metaethics', 2),
  ('philosophy', 'ethics', 'applied-ethics', 'Applied ethics', 3),
  ('philosophy', 'epistemology', 'knowledge-and-belief', 'Knowledge and belief', 1),
  ('philosophy', 'epistemology', 'justification', 'Justification', 2),
  ('philosophy', 'epistemology', 'scepticism', 'Scepticism', 3),
  ('philosophy', 'aesthetics', 'art-and-beauty', 'Art and beauty', 1),
  ('philosophy', 'aesthetics', 'judgement-and-taste', 'Judgement and taste', 2),
  ('philosophy', 'philosophy-of-religion', 'arguments-for-god', 'Arguments for God', 1),
  ('philosophy', 'philosophy-of-religion', 'problem-of-evil', 'Problem of evil', 2),
  ('philosophy', 'philosophy-of-religion', 'religious-language', 'Religious language', 3),
  ('philosophy', 'political-philosophy', 'political-obligation', 'Political obligation', 1),
  ('philosophy', 'political-philosophy', 'justice', 'Justice', 2),
  ('philosophy', 'political-philosophy', 'liberty-and-equality', 'Liberty and equality', 3),
  ('philosophy', 'philosophy-of-science', 'scientific-method', 'Scientific method', 1),
  ('philosophy', 'philosophy-of-science', 'realism-and-anti-realism', 'Realism and anti-realism', 2),
  ('philosophy', 'reading-the-text', 'analysis-of-arguments', 'Analysis of arguments', 1),
  ('philosophy', 'reading-the-text', 'contextual-understanding', 'Contextual understanding', 2),
  ('philosophy', 'doing-philosophy', 'nature-of-philosophical-activity', 'Nature of philosophical activity', 1),
  ('philosophy', 'doing-philosophy', 'methods-and-value-of-philosophy', 'Methods and value of philosophy', 2),
  ('world-religions', 'hinduism', 'beliefs-and-texts', 'Beliefs and texts', 1),
  ('world-religions', 'hinduism', 'practices-and-rituals', 'Practices and rituals', 2),
  ('world-religions', 'buddhism', 'four-noble-truths', 'Four Noble Truths', 1),
  ('world-religions', 'buddhism', 'practices-and-meditation', 'Practices and meditation', 2),
  ('world-religions', 'sikhism', 'beliefs-and-the-gurus', 'Beliefs and the Gurus', 1),
  ('world-religions', 'sikhism', 'practices-and-the-gurdwara', 'Practices and the Gurdwara', 2),
  ('world-religions', 'judaism', 'beliefs-and-torah', 'Beliefs and Torah', 1),
  ('world-religions', 'judaism', 'festivals-and-practice', 'Festivals and practice', 2),
  ('world-religions', 'christianity', 'beliefs-and-scripture', 'Beliefs and scripture', 1),
  ('world-religions', 'christianity', 'worship-and-sacraments', 'Worship and sacraments', 2),
  ('world-religions', 'islam', 'beliefs-and-quran', 'Beliefs and Qur''an', 1),
  ('world-religions', 'islam', 'five-pillars', 'Five Pillars', 2),
  ('world-religions', 'jainism', 'beliefs-and-ahimsa', 'Beliefs and ahimsa', 1),
  ('world-religions', 'jainism', 'practices', 'Practices', 2),
  ('world-religions', 'taoism', 'beliefs-and-the-tao', 'Beliefs and the Tao', 1),
  ('world-religions', 'taoism', 'practices', 'Practices', 2),
  ('world-religions', 'rituals-and-practices', 'rites-of-passage', 'Rites of passage', 1),
  ('world-religions', 'rituals-and-practices', 'pilgrimage', 'Pilgrimage', 2),
  ('world-religions', 'rituals-and-practices', 'worship', 'Worship', 3),
  ('world-religions', 'religious-experience', 'mysticism', 'Mysticism', 1),
  ('world-religions', 'religious-experience', 'prayer-and-meditation', 'Prayer and meditation', 2),
  ('world-religions', 'ethics-and-religion', 'moral-teaching', 'Moral teaching', 1),
  ('world-religions', 'ethics-and-religion', 'contemporary-issues', 'Contemporary issues', 2),
  ('world-religions', 'religion-and-society', 'religion-and-identity', 'Religion and identity', 1),
  ('world-religions', 'religion-and-society', 'interfaith-dialogue', 'Interfaith dialogue', 2)
) as st(subject_slug, topic_slug, slug, name, sort_order) on st.subject_slug = s.slug
join public.topics tp on tp.subject_id = s.id and tp.slug = st.topic_slug
on conflict (topic_id, slug) do update set
  name = excluded.name, sort_order = excluded.sort_order;
